"""updated db

Revision ID: 54c496cd5259
Revises: c7cc0f6ffa53
Create Date: 2026-01-20 04:41:30.848338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c496cd5259'
down_revision = 'c7cc0f6ffa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requestor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('country')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('at')
        batch_op.drop_column('requestor')

    # ### end Alembic commands ###
